import { StyleSheet } from 'react-native';
import { Theme } from '../../theme';
import { moderateScale, verticalScale, normalize } from '../../theme/scale';
import { fonts } from '../../theme/fonts';

export const styles = (theme: Theme) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: theme.colors.background,
        },
        scrollContent: {
            paddingBottom: verticalScale(100),
        },
        header: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: moderateScale(16),
            paddingVertical: verticalScale(12),
        },
        headerLeft: {
            flexDirection: 'row',
            alignItems: 'center',
            flex: 1,
        },
        backButton: {
            width: moderateScale(40),
            height: moderateScale(40),
            borderRadius: moderateScale(10),
            backgroundColor: theme.colors.background,
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: moderateScale(12),
            borderWidth: 1,
            borderColor: theme.colors.border,
        },
        userAvatar: {
            width: moderateScale(40),
            height: moderateScale(40),
            borderRadius: moderateScale(20),
            marginRight: moderateScale(12),
        },
        userName: {
            fontSize: normalize(18),
            fontFamily: fonts.bold,
            color: theme.colors.text,
        },
        menuButton: {
            padding: moderateScale(8),
        },
        menuPopup: {
            position: 'absolute',
            top: verticalScale(50),
            right: moderateScale(16),
            backgroundColor: theme.colors.surface,
            borderRadius: moderateScale(8),
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 4,
            elevation: 5,
            padding: moderateScale(12),
            zIndex: 100,
        },
        menuItem: {
            fontSize: normalize(14),
            fontFamily: fonts.medium,
            color: theme.colors.text,
        },
        card: {
            margin: moderateScale(16),
            borderRadius: moderateScale(12),
            borderWidth: 1,
            borderColor: theme.colors.border,
            padding: moderateScale(16),
        },
        detailItem: {
        },
        label: {
            fontSize: normalize(12),
            fontFamily: fonts.regular,
            color: theme.colors.mutedText,
            marginBottom: verticalScale(4),
        },
        value: {
            fontSize: normalize(14),
            fontFamily: fonts.medium,
            color: theme.colors.text,
            lineHeight: normalize(20),
        },
        divider: {
            height: 1,
            backgroundColor: theme.colors.border,
            marginBottom: verticalScale(16),
        },
        footer: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            paddingHorizontal: moderateScale(16),
            paddingVertical: verticalScale(20),
            backgroundColor: theme.colors.background,
            position: 'absolute',
            bottom: 0,
            left: 0,
            right: 0,
        },
        rejectButton: {
            flex: 1,
            height: verticalScale(50),
            borderRadius: moderateScale(10),
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: theme.colors.border,
            marginRight: moderateScale(12),
            backgroundColor: theme.colors.surface,
        },
        rejectText: {
            fontSize: normalize(16),
            fontFamily: fonts.bold,
            color: theme.colors.text,
        },
        acceptButton: {
            flex: 1,
            height: verticalScale(50),
            borderRadius: moderateScale(10),
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: theme.colors.brandGreen,
        },
        acceptText: {
            fontSize: normalize(16),
            fontFamily: fonts.bold,
            color: theme.colors.onPrimary || '#FFF',
        },
        loadingOverlay: {
            ...StyleSheet.absoluteFillObject,
            backgroundColor: 'rgba(255, 255, 255, 0.7)',
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 1000,
        },
        modalOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            justifyContent: 'center',
            alignItems: 'center',
        },
        modalContainer: {
            width: '90%',
            backgroundColor: theme.colors.surface,
            borderRadius: moderateScale(20),
            padding: moderateScale(24),
            elevation: 5,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
        },
        modalTitle: {
            fontSize: normalize(20),
            fontFamily: fonts.bold,
            color: theme.colors.text,
            marginBottom: verticalScale(8),
        },
        modalSubtitle: {
            fontSize: normalize(14),
            fontFamily: fonts.regular,
            color: theme.colors.mutedText,
            marginBottom: verticalScale(20),
            lineHeight: normalize(20),
        },
        reasonInput: {
            height: verticalScale(120),
            borderWidth: 1,
            borderColor: theme.colors.border,
            borderRadius: moderateScale(12),
            padding: moderateScale(12),
            fontSize: normalize(14),
            fontFamily: fonts.regular,
            color: theme.colors.text,
            textAlignVertical: 'top',
            marginBottom: verticalScale(24),
        },
        modalActions: {
            flexDirection: 'row',
            justifyContent: 'space-between',
        },
        modalCancelButton: {
            flex: 1,
            height: verticalScale(48),
            borderRadius: moderateScale(12),
            borderWidth: 1,
            borderColor: theme.colors.border,
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: moderateScale(12),
        },
        modalConfirmButton: {
            flex: 1,
            height: verticalScale(48),
            borderRadius: moderateScale(12),
            backgroundColor: theme.colors.brandGreen,
            justifyContent: 'center',
            alignItems: 'center',
        },
        modalCancelText: {
            fontSize: normalize(16),
            fontFamily: fonts.bold,
            color: theme.colors.text,
        },
        modalConfirmText: {
            fontSize: normalize(16),
            fontFamily: fonts.bold,
            color: theme.colors.onPrimary || '#FFF',
        },
    });
